# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='iframeUrl',
        ),
        migrations.RemoveField(
            model_name='post',
            name='mainImgUrl',
        ),
        migrations.RemoveField(
            model_name='post',
            name='splashImgUrl',
        ),
        migrations.AddField(
            model_name='post',
            name='iframe_url',
            field=models.URLField(default='', max_length=1999, verbose_name='iFrame URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='main_img_url',
            field=models.URLField(default='', max_length=1999, verbose_name='Image URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='splash_img_url',
            field=models.URLField(default='', max_length=1999, verbose_name='Splash Image URL'),
            preserve_default=False,
        ),
    ]
