# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20170317_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='isFirstFeature',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='post',
            name='isSecondFeature',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='post',
            name='isThirdFeature',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
