# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20170320_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagefeature',
            name='slug',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
