# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20170328_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='upload_img',
            field=models.FileField(blank=True, upload_to='uploads/', verbose_name='Image Uploader'),
        ),
    ]
