# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_post_upload_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('upload_img', models.FileField(blank=True, upload_to='uploads/images/', verbose_name='Image Uploader')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='upload_img',
        ),
        migrations.AlterField(
            model_name='post',
            name='main_img_url',
            field=models.URLField(blank=True, max_length=1999, verbose_name='Image URL'),
        ),
    ]
