# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20170329_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='gif_url',
        ),
        migrations.AlterField(
            model_name='post',
            name='main_img_url',
            field=models.URLField(max_length=1999, verbose_name='Image URL'),
        ),
    ]
