# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 23:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20170329_1824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepagefeature',
            options={'ordering': ('-id',)},
        ),
    ]
