# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 00:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20170329_1843'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-published_date', '-created_date')},
        ),
    ]
