// map actions

export const REQUEST_ALL_POSTS = 'REQUEST_ALL_POSTS';
export const RECIEVE_ALL_POSTS = 'RECIEVE_ALL_POSTS';

export const REQUEST_ALL_HP_FEATURES = 'REQUEST_ALL_HP_FEATURES';
export const RECIEVE_ALL_HP_FEATURES = 'RECIEVE_ALL_HP_FEATURES';